version: 0

homeserver:
    # Server name list support multi-tenant, specify only one element most of time. 
    server_name: [ligase]
    server_from_db: false

# Specify your host, port for kafka connection.
transport_configs:
    - addresses: kafka:9092
      underlying: kafka
      name: kafka

# Only kafka underlying avaliable, nats is not supported any more.
kafka:
    statistics:
        producer_interval: 2000
        consumer_interval: 2000
    common_cfg:
        enable_idempotence: true
        force_async_send: false
        replica_factor: 1
        num_partitions: 3
        num_producers: 3
    producers:
        db_updates:
            topic: dbUpdates
            underlying: kafka
            name: dbUpdatesProd
        dispatch_output:
            topic: dispatch-out
            underlying: kafka
            name: dispatchOutProd
        fedapi_output:
            topic: fedapi-out
            underlying: kafka
            name: fedapiOutProd
        get_missing_event:
            topic: getmissingevent
            underlying: kafka
            name: fedGetMissingEventProd
        download_media:
            topic: downloadmedia
            underlying: kafka
            name: fedDownloadMediaProd
        input_room_event:
            topic: roomserverInput
            underlying: kafka
            name: roomserverInputProd
            inst: 3
            linger_ms: 0.1
    consumers:
        dispatch_input:
            topic: fed
            group: dispatch
            underlying: kafka
            name: dispatchInCons
        fedsenser_input:
            topic: dispatch-out
            group: dispatch
            underlying: kafka
            name: fedsenderInCons
            topic_auto_offset_reset: earliest
        fedapi_input:
            topic: fedapi-in
            group: dispatch
            underlying: kafka
            name: fedapiOutCons
        fed_backfill:
            topic: fedapi-in
            group: backfill
            underlying: kafka
            name: fedbackfillCons
        edusender_input:
            topic: fedEduOut
            group: dispatch
            underlying: kafka
            name: edusenderInCons
        setting_update:
            topic: settingUpdate
            group: settingUpdate-fed
            underlying: kafka
            name: fedsettingupdateCons
        get_missing_event:
            topic: getmissingevent
            group: getmissingevent-fed
            underlying: kafka
            name: fedGetMissingEventCons

nats:
    uri: nats://nats:4222

rpc:
    rs_qry_topic: roomserver_query
    pr_qry_topic: publicrooms_query
    alias_topic: roomserver_alias
    room_input_topic: roomserver_input
    fed_topic: fed
    fed_alias_topic: fed.roomserver_alias
    fed_profile_topic: fed.profile
    fed_avatar_topic: fed.avatar
    fed_displayname_topic: fed.displayname
    fed_rs_qry_topic: fed.roomstate
    fed_download_topic: fed.download
    fed_invite_topic: fed.invite
    fed_user_info_topic: fed.user_info
    fed_makejoin_topic: fed.makejoin
    fed_sendjoin_topic: fed.sendjoin
    fed_makeleave_topic: fed.makeleave
    fed_sendleave_topic: fed.sendleave

database:
    create_db:
        driver: postgres
        addresses: postgres://postgres:postgres@pg-master:5432/postgres?sslmode=disable
    room_server:
        driver: postgres
        addresses: postgres://postgres:postgres@pg-master:5432/dendrite_roomserver?sslmode=disable
    federation:
        driver: postgres
        addresses: postgres://postgres:postgres@pg-master:5432/dendrite_federation?sslmode=disable
    server_conf:
        driver: postgres
        addresses: postgres://postgres:postgres@pg-master:5432/dendrite_serverconf?sslmode=disable
    server_key:
        driver: postgres
        addresses: postgres://postgres:postgres@pg-master:5432/dendrite_serverkey?sslmode=disable
    encryption:
        driver: postgres
        addresses: postgres://postgres:postgres@pg-master:5432/dendrite_encryptapi?sslmode=disable
    account:
        driver: postgres
        addresses: postgres://postgres:postgres@pg-master:5432/dendrite_account?sslmode=disable
    use_sync: false

# Specify your host, port, username and password for redis, nats and database connection.
# If you run by steps in INSTALL.md, just change the ip below to your own host.
redis:
    uris:
      - redis://redis:6379/0

media:
    # To be implemented.
    upload_url: upload_url_prefix?type=%s&thumbnail=%s

log:
    level: info
    files: [./log/fed.log]
    underlying: zap
    redirect_stderr: false
    write_to_stdout: true
    zap_config:
        max_size: 100
        max_backups: 100
        localtime: true
        compress: true
        json_format: false
        bt_enabled: false
        bt_level: error
        field_separator: space

cache:
    durationDefault: 900
    durationRefresh: 900

gc_timer: 0
