// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.27.1
// 	protoc        v3.17.3
// source: rcs.proto

package pb

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type HandleEventByRcsRsp struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Events  []*Event `protobuf:"bytes,1,rep,name=events,proto3" json:"events,omitempty"`
	Succeed bool     `protobuf:"varint,2,opt,name=succeed,proto3" json:"succeed,omitempty"`
}

func (x *HandleEventByRcsRsp) Reset() {
	*x = HandleEventByRcsRsp{}
	if protoimpl.UnsafeEnabled {
		mi := &file_rcs_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *HandleEventByRcsRsp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*HandleEventByRcsRsp) ProtoMessage() {}

func (x *HandleEventByRcsRsp) ProtoReflect() protoreflect.Message {
	mi := &file_rcs_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use HandleEventByRcsRsp.ProtoReflect.Descriptor instead.
func (*HandleEventByRcsRsp) Descriptor() ([]byte, []int) {
	return file_rcs_proto_rawDescGZIP(), []int{0}
}

func (x *HandleEventByRcsRsp) GetEvents() []*Event {
	if x != nil {
		return x.Events
	}
	return nil
}

func (x *HandleEventByRcsRsp) GetSucceed() bool {
	if x != nil {
		return x.Succeed
	}
	return false
}

var File_rcs_proto protoreflect.FileDescriptor

var file_rcs_proto_rawDesc = []byte{
	0x0a, 0x09, 0x72, 0x63, 0x73, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12, 0x02, 0x70, 0x62, 0x1a,
	0x0c, 0x63, 0x6f, 0x6d, 0x6d, 0x6f, 0x6e, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x22, 0x52, 0x0a,
	0x13, 0x48, 0x61, 0x6e, 0x64, 0x6c, 0x65, 0x45, 0x76, 0x65, 0x6e, 0x74, 0x42, 0x79, 0x52, 0x63,
	0x73, 0x52, 0x73, 0x70, 0x12, 0x21, 0x0a, 0x06, 0x65, 0x76, 0x65, 0x6e, 0x74, 0x73, 0x18, 0x01,
	0x20, 0x03, 0x28, 0x0b, 0x32, 0x09, 0x2e, 0x70, 0x62, 0x2e, 0x45, 0x76, 0x65, 0x6e, 0x74, 0x52,
	0x06, 0x65, 0x76, 0x65, 0x6e, 0x74, 0x73, 0x12, 0x18, 0x0a, 0x07, 0x73, 0x75, 0x63, 0x63, 0x65,
	0x65, 0x64, 0x18, 0x02, 0x20, 0x01, 0x28, 0x08, 0x52, 0x07, 0x73, 0x75, 0x63, 0x63, 0x65, 0x65,
	0x64, 0x32, 0x45, 0x0a, 0x09, 0x52, 0x63, 0x73, 0x53, 0x65, 0x72, 0x76, 0x65, 0x72, 0x12, 0x38,
	0x0a, 0x10, 0x48, 0x61, 0x6e, 0x64, 0x6c, 0x65, 0x45, 0x76, 0x65, 0x6e, 0x74, 0x42, 0x79, 0x52,
	0x63, 0x73, 0x12, 0x09, 0x2e, 0x70, 0x62, 0x2e, 0x45, 0x76, 0x65, 0x6e, 0x74, 0x1a, 0x17, 0x2e,
	0x70, 0x62, 0x2e, 0x48, 0x61, 0x6e, 0x64, 0x6c, 0x65, 0x45, 0x76, 0x65, 0x6e, 0x74, 0x42, 0x79,
	0x52, 0x63, 0x73, 0x52, 0x73, 0x70, 0x22, 0x00, 0x42, 0x07, 0x5a, 0x05, 0x2e, 0x2f, 0x3b, 0x70,
	0x62, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_rcs_proto_rawDescOnce sync.Once
	file_rcs_proto_rawDescData = file_rcs_proto_rawDesc
)

func file_rcs_proto_rawDescGZIP() []byte {
	file_rcs_proto_rawDescOnce.Do(func() {
		file_rcs_proto_rawDescData = protoimpl.X.CompressGZIP(file_rcs_proto_rawDescData)
	})
	return file_rcs_proto_rawDescData
}

var file_rcs_proto_msgTypes = make([]protoimpl.MessageInfo, 1)
var file_rcs_proto_goTypes = []interface{}{
	(*HandleEventByRcsRsp)(nil), // 0: pb.HandleEventByRcsRsp
	(*Event)(nil),               // 1: pb.Event
}
var file_rcs_proto_depIdxs = []int32{
	1, // 0: pb.HandleEventByRcsRsp.events:type_name -> pb.Event
	1, // 1: pb.RcsServer.HandleEventByRcs:input_type -> pb.Event
	0, // 2: pb.RcsServer.HandleEventByRcs:output_type -> pb.HandleEventByRcsRsp
	2, // [2:3] is the sub-list for method output_type
	1, // [1:2] is the sub-list for method input_type
	1, // [1:1] is the sub-list for extension type_name
	1, // [1:1] is the sub-list for extension extendee
	0, // [0:1] is the sub-list for field type_name
}

func init() { file_rcs_proto_init() }
func file_rcs_proto_init() {
	if File_rcs_proto != nil {
		return
	}
	file_common_proto_init()
	if !protoimpl.UnsafeEnabled {
		file_rcs_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*HandleEventByRcsRsp); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_rcs_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   1,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_rcs_proto_goTypes,
		DependencyIndexes: file_rcs_proto_depIdxs,
		MessageInfos:      file_rcs_proto_msgTypes,
	}.Build()
	File_rcs_proto = out.File
	file_rcs_proto_rawDesc = nil
	file_rcs_proto_goTypes = nil
	file_rcs_proto_depIdxs = nil
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConnInterface

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion6

// RcsServerClient is the client API for RcsServer service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type RcsServerClient interface {
	HandleEventByRcs(ctx context.Context, in *Event, opts ...grpc.CallOption) (*HandleEventByRcsRsp, error)
}

type rcsServerClient struct {
	cc grpc.ClientConnInterface
}

func NewRcsServerClient(cc grpc.ClientConnInterface) RcsServerClient {
	return &rcsServerClient{cc}
}

func (c *rcsServerClient) HandleEventByRcs(ctx context.Context, in *Event, opts ...grpc.CallOption) (*HandleEventByRcsRsp, error) {
	out := new(HandleEventByRcsRsp)
	err := c.cc.Invoke(ctx, "/pb.RcsServer/HandleEventByRcs", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// RcsServerServer is the server API for RcsServer service.
type RcsServerServer interface {
	HandleEventByRcs(context.Context, *Event) (*HandleEventByRcsRsp, error)
}

// UnimplementedRcsServerServer can be embedded to have forward compatible implementations.
type UnimplementedRcsServerServer struct {
}

func (*UnimplementedRcsServerServer) HandleEventByRcs(context.Context, *Event) (*HandleEventByRcsRsp, error) {
	return nil, status.Errorf(codes.Unimplemented, "method HandleEventByRcs not implemented")
}

func RegisterRcsServerServer(s *grpc.Server, srv RcsServerServer) {
	s.RegisterService(&_RcsServer_serviceDesc, srv)
}

func _RcsServer_HandleEventByRcs_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(Event)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(RcsServerServer).HandleEventByRcs(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/pb.RcsServer/HandleEventByRcs",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(RcsServerServer).HandleEventByRcs(ctx, req.(*Event))
	}
	return interceptor(ctx, in, info, handler)
}

var _RcsServer_serviceDesc = grpc.ServiceDesc{
	ServiceName: "pb.RcsServer",
	HandlerType: (*RcsServerServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "HandleEventByRcs",
			Handler:    _RcsServer_HandleEventByRcs_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "rcs.proto",
}
