// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.26.0
// 	protoc        v3.15.8
// source: sync.proto

package pb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type UnreadNotifications struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	HighLightCount    int64 `protobuf:"varint,1,opt,name=highLightCount,proto3" json:"highLightCount,omitempty"`
	NotificationCount int64 `protobuf:"varint,2,opt,name=notificationCount,proto3" json:"notificationCount,omitempty"`
}

func (x *UnreadNotifications) Reset() {
	*x = UnreadNotifications{}
	if protoimpl.UnsafeEnabled {
		mi := &file_sync_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *UnreadNotifications) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UnreadNotifications) ProtoMessage() {}

func (x *UnreadNotifications) ProtoReflect() protoreflect.Message {
	mi := &file_sync_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UnreadNotifications.ProtoReflect.Descriptor instead.
func (*UnreadNotifications) Descriptor() ([]byte, []int) {
	return file_sync_proto_rawDescGZIP(), []int{0}
}

func (x *UnreadNotifications) GetHighLightCount() int64 {
	if x != nil {
		return x.HighLightCount
	}
	return 0
}

func (x *UnreadNotifications) GetNotificationCount() int64 {
	if x != nil {
		return x.NotificationCount
	}
	return 0
}

type JoinResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	State       *JoinResponse_State       `protobuf:"bytes,1,opt,name=state,proto3" json:"state,omitempty"`
	Timeline    *JoinResponse_Timeline    `protobuf:"bytes,2,opt,name=timeline,proto3" json:"timeline,omitempty"`
	Ephemeral   *JoinResponse_Ephemeral   `protobuf:"bytes,3,opt,name=ephemeral,proto3" json:"ephemeral,omitempty"`
	AccountData *JoinResponse_AccountData `protobuf:"bytes,4,opt,name=accountData,proto3" json:"accountData,omitempty"`
	Unread      *UnreadNotifications      `protobuf:"bytes,5,opt,name=unread,proto3" json:"unread,omitempty"`
}

func (x *JoinResponse) Reset() {
	*x = JoinResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_sync_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *JoinResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*JoinResponse) ProtoMessage() {}

func (x *JoinResponse) ProtoReflect() protoreflect.Message {
	mi := &file_sync_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use JoinResponse.ProtoReflect.Descriptor instead.
func (*JoinResponse) Descriptor() ([]byte, []int) {
	return file_sync_proto_rawDescGZIP(), []int{1}
}

func (x *JoinResponse) GetState() *JoinResponse_State {
	if x != nil {
		return x.State
	}
	return nil
}

func (x *JoinResponse) GetTimeline() *JoinResponse_Timeline {
	if x != nil {
		return x.Timeline
	}
	return nil
}

func (x *JoinResponse) GetEphemeral() *JoinResponse_Ephemeral {
	if x != nil {
		return x.Ephemeral
	}
	return nil
}

func (x *JoinResponse) GetAccountData() *JoinResponse_AccountData {
	if x != nil {
		return x.AccountData
	}
	return nil
}

func (x *JoinResponse) GetUnread() *UnreadNotifications {
	if x != nil {
		return x.Unread
	}
	return nil
}

type InviteResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	InviteState *InviteResponse_InviteState `protobuf:"bytes,1,opt,name=inviteState,proto3" json:"inviteState,omitempty"`
}

func (x *InviteResponse) Reset() {
	*x = InviteResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_sync_proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *InviteResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*InviteResponse) ProtoMessage() {}

func (x *InviteResponse) ProtoReflect() protoreflect.Message {
	mi := &file_sync_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use InviteResponse.ProtoReflect.Descriptor instead.
func (*InviteResponse) Descriptor() ([]byte, []int) {
	return file_sync_proto_rawDescGZIP(), []int{2}
}

func (x *InviteResponse) GetInviteState() *InviteResponse_InviteState {
	if x != nil {
		return x.InviteState
	}
	return nil
}

type LeaveResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	State    *LeaveResponse_State    `protobuf:"bytes,1,opt,name=state,proto3" json:"state,omitempty"`
	Timeline *LeaveResponse_Timeline `protobuf:"bytes,2,opt,name=timeline,proto3" json:"timeline,omitempty"`
}

func (x *LeaveResponse) Reset() {
	*x = LeaveResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_sync_proto_msgTypes[3]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *LeaveResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*LeaveResponse) ProtoMessage() {}

func (x *LeaveResponse) ProtoReflect() protoreflect.Message {
	mi := &file_sync_proto_msgTypes[3]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use LeaveResponse.ProtoReflect.Descriptor instead.
func (*LeaveResponse) Descriptor() ([]byte, []int) {
	return file_sync_proto_rawDescGZIP(), []int{3}
}

func (x *LeaveResponse) GetState() *LeaveResponse_State {
	if x != nil {
		return x.State
	}
	return nil
}

func (x *LeaveResponse) GetTimeline() *LeaveResponse_Timeline {
	if x != nil {
		return x.Timeline
	}
	return nil
}

type Pusher struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	UserName          string `protobuf:"bytes,1,opt,name=userName,proto3" json:"userName,omitempty"`
	DeviceID          string `protobuf:"bytes,2,opt,name=deviceID,proto3" json:"deviceID,omitempty"`
	PushKey           string `protobuf:"bytes,3,opt,name=pushKey,proto3" json:"pushKey,omitempty"`
	PushKeyTs         int64  `protobuf:"varint,4,opt,name=pushKeyTs,proto3" json:"pushKeyTs,omitempty"`
	Kind              string `protobuf:"bytes,5,opt,name=kind,proto3" json:"kind,omitempty"`
	AppId             string `protobuf:"bytes,6,opt,name=appId,proto3" json:"appId,omitempty"`
	AppDisplayName    string `protobuf:"bytes,7,opt,name=appDisplayName,proto3" json:"appDisplayName,omitempty"`
	DeviceDisplayName string `protobuf:"bytes,8,opt,name=deviceDisplayName,proto3" json:"deviceDisplayName,omitempty"`
	ProfileTag        string `protobuf:"bytes,9,opt,name=profileTag,proto3" json:"profileTag,omitempty"`
	Lang              string `protobuf:"bytes,10,opt,name=lang,proto3" json:"lang,omitempty"`
	Append            bool   `protobuf:"varint,11,opt,name=append,proto3" json:"append,omitempty"`
	Data              []byte `protobuf:"bytes,12,opt,name=data,proto3" json:"data,omitempty"`
}

func (x *Pusher) Reset() {
	*x = Pusher{}
	if protoimpl.UnsafeEnabled {
		mi := &file_sync_proto_msgTypes[4]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Pusher) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Pusher) ProtoMessage() {}

func (x *Pusher) ProtoReflect() protoreflect.Message {
	mi := &file_sync_proto_msgTypes[4]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Pusher.ProtoReflect.Descriptor instead.
func (*Pusher) Descriptor() ([]byte, []int) {
	return file_sync_proto_rawDescGZIP(), []int{4}
}

func (x *Pusher) GetUserName() string {
	if x != nil {
		return x.UserName
	}
	return ""
}

func (x *Pusher) GetDeviceID() string {
	if x != nil {
		return x.DeviceID
	}
	return ""
}

func (x *Pusher) GetPushKey() string {
	if x != nil {
		return x.PushKey
	}
	return ""
}

func (x *Pusher) GetPushKeyTs() int64 {
	if x != nil {
		return x.PushKeyTs
	}
	return 0
}

func (x *Pusher) GetKind() string {
	if x != nil {
		return x.Kind
	}
	return ""
}

func (x *Pusher) GetAppId() string {
	if x != nil {
		return x.AppId
	}
	return ""
}

func (x *Pusher) GetAppDisplayName() string {
	if x != nil {
		return x.AppDisplayName
	}
	return ""
}

func (x *Pusher) GetDeviceDisplayName() string {
	if x != nil {
		return x.DeviceDisplayName
	}
	return ""
}

func (x *Pusher) GetProfileTag() string {
	if x != nil {
		return x.ProfileTag
	}
	return ""
}

func (x *Pusher) GetLang() string {
	if x != nil {
		return x.Lang
	}
	return ""
}

func (x *Pusher) GetAppend() bool {
	if x != nil {
		return x.Append
	}
	return false
}

func (x *Pusher) GetData() []byte {
	if x != nil {
		return x.Data
	}
	return nil
}

type Pushers struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Pushers []*Pusher `protobuf:"bytes,1,rep,name=pushers,proto3" json:"pushers,omitempty"`
}

func (x *Pushers) Reset() {
	*x = Pushers{}
	if protoimpl.UnsafeEnabled {
		mi := &file_sync_proto_msgTypes[5]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Pushers) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Pushers) ProtoMessage() {}

func (x *Pushers) ProtoReflect() protoreflect.Message {
	mi := &file_sync_proto_msgTypes[5]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Pushers.ProtoReflect.Descriptor instead.
func (*Pushers) Descriptor() ([]byte, []int) {
	return file_sync_proto_rawDescGZIP(), []int{5}
}

func (x *Pushers) GetPushers() []*Pusher {
	if x != nil {
		return x.Pushers
	}
	return nil
}

type PushCondition struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Kind    string `protobuf:"bytes,1,opt,name=kind,proto3" json:"kind,omitempty"`
	Key     string `protobuf:"bytes,2,opt,name=key,proto3" json:"key,omitempty"`
	Pattern string `protobuf:"bytes,3,opt,name=pattern,proto3" json:"pattern,omitempty"`
	Is      string `protobuf:"bytes,4,opt,name=is,proto3" json:"is,omitempty"`
}

func (x *PushCondition) Reset() {
	*x = PushCondition{}
	if protoimpl.UnsafeEnabled {
		mi := &file_sync_proto_msgTypes[6]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *PushCondition) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PushCondition) ProtoMessage() {}

func (x *PushCondition) ProtoReflect() protoreflect.Message {
	mi := &file_sync_proto_msgTypes[6]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PushCondition.ProtoReflect.Descriptor instead.
func (*PushCondition) Descriptor() ([]byte, []int) {
	return file_sync_proto_rawDescGZIP(), []int{6}
}

func (x *PushCondition) GetKind() string {
	if x != nil {
		return x.Kind
	}
	return ""
}

func (x *PushCondition) GetKey() string {
	if x != nil {
		return x.Key
	}
	return ""
}

func (x *PushCondition) GetPattern() string {
	if x != nil {
		return x.Pattern
	}
	return ""
}

func (x *PushCondition) GetIs() string {
	if x != nil {
		return x.Is
	}
	return ""
}

type PushRule struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Actions    []byte           `protobuf:"bytes,1,opt,name=Actions,proto3" json:"Actions,omitempty"`
	Default    bool             `protobuf:"varint,2,opt,name=default,proto3" json:"default,omitempty"`
	Enabled    bool             `protobuf:"varint,3,opt,name=enabled,proto3" json:"enabled,omitempty"`
	RuleId     string           `protobuf:"bytes,4,opt,name=ruleId,proto3" json:"ruleId,omitempty"`
	Conditions []*PushCondition `protobuf:"bytes,5,rep,name=conditions,proto3" json:"conditions,omitempty"`
	Pattern    string           `protobuf:"bytes,6,opt,name=pattern,proto3" json:"pattern,omitempty"`
}

func (x *PushRule) Reset() {
	*x = PushRule{}
	if protoimpl.UnsafeEnabled {
		mi := &file_sync_proto_msgTypes[7]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *PushRule) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PushRule) ProtoMessage() {}

func (x *PushRule) ProtoReflect() protoreflect.Message {
	mi := &file_sync_proto_msgTypes[7]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PushRule.ProtoReflect.Descriptor instead.
func (*PushRule) Descriptor() ([]byte, []int) {
	return file_sync_proto_rawDescGZIP(), []int{7}
}

func (x *PushRule) GetActions() []byte {
	if x != nil {
		return x.Actions
	}
	return nil
}

func (x *PushRule) GetDefault() bool {
	if x != nil {
		return x.Default
	}
	return false
}

func (x *PushRule) GetEnabled() bool {
	if x != nil {
		return x.Enabled
	}
	return false
}

func (x *PushRule) GetRuleId() string {
	if x != nil {
		return x.RuleId
	}
	return ""
}

func (x *PushRule) GetConditions() []*PushCondition {
	if x != nil {
		return x.Conditions
	}
	return nil
}

func (x *PushRule) GetPattern() string {
	if x != nil {
		return x.Pattern
	}
	return ""
}

type Rules struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Content   []*PushRule `protobuf:"bytes,1,rep,name=content,proto3" json:"content,omitempty"`
	Override  []*PushRule `protobuf:"bytes,2,rep,name=override,proto3" json:"override,omitempty"`
	Room      []*PushRule `protobuf:"bytes,3,rep,name=room,proto3" json:"room,omitempty"`
	Sender    []*PushRule `protobuf:"bytes,4,rep,name=sender,proto3" json:"sender,omitempty"`
	UnderRide []*PushRule `protobuf:"bytes,5,rep,name=underRide,proto3" json:"underRide,omitempty"`
}

func (x *Rules) Reset() {
	*x = Rules{}
	if protoimpl.UnsafeEnabled {
		mi := &file_sync_proto_msgTypes[8]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Rules) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Rules) ProtoMessage() {}

func (x *Rules) ProtoReflect() protoreflect.Message {
	mi := &file_sync_proto_msgTypes[8]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Rules.ProtoReflect.Descriptor instead.
func (*Rules) Descriptor() ([]byte, []int) {
	return file_sync_proto_rawDescGZIP(), []int{8}
}

func (x *Rules) GetContent() []*PushRule {
	if x != nil {
		return x.Content
	}
	return nil
}

func (x *Rules) GetOverride() []*PushRule {
	if x != nil {
		return x.Override
	}
	return nil
}

func (x *Rules) GetRoom() []*PushRule {
	if x != nil {
		return x.Room
	}
	return nil
}

func (x *Rules) GetSender() []*PushRule {
	if x != nil {
		return x.Sender
	}
	return nil
}

func (x *Rules) GetUnderRide() []*PushRule {
	if x != nil {
		return x.UnderRide
	}
	return nil
}

type JoinResponse_State struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Events []*ClientEvent `protobuf:"bytes,1,rep,name=events,proto3" json:"events,omitempty"`
}

func (x *JoinResponse_State) Reset() {
	*x = JoinResponse_State{}
	if protoimpl.UnsafeEnabled {
		mi := &file_sync_proto_msgTypes[9]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *JoinResponse_State) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*JoinResponse_State) ProtoMessage() {}

func (x *JoinResponse_State) ProtoReflect() protoreflect.Message {
	mi := &file_sync_proto_msgTypes[9]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use JoinResponse_State.ProtoReflect.Descriptor instead.
func (*JoinResponse_State) Descriptor() ([]byte, []int) {
	return file_sync_proto_rawDescGZIP(), []int{1, 0}
}

func (x *JoinResponse_State) GetEvents() []*ClientEvent {
	if x != nil {
		return x.Events
	}
	return nil
}

type JoinResponse_Timeline struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Events    []*ClientEvent `protobuf:"bytes,1,rep,name=events,proto3" json:"events,omitempty"`
	Limited   bool           `protobuf:"varint,2,opt,name=limited,proto3" json:"limited,omitempty"`
	PrevBatch string         `protobuf:"bytes,3,opt,name=prevBatch,proto3" json:"prevBatch,omitempty"`
}

func (x *JoinResponse_Timeline) Reset() {
	*x = JoinResponse_Timeline{}
	if protoimpl.UnsafeEnabled {
		mi := &file_sync_proto_msgTypes[10]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *JoinResponse_Timeline) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*JoinResponse_Timeline) ProtoMessage() {}

func (x *JoinResponse_Timeline) ProtoReflect() protoreflect.Message {
	mi := &file_sync_proto_msgTypes[10]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use JoinResponse_Timeline.ProtoReflect.Descriptor instead.
func (*JoinResponse_Timeline) Descriptor() ([]byte, []int) {
	return file_sync_proto_rawDescGZIP(), []int{1, 1}
}

func (x *JoinResponse_Timeline) GetEvents() []*ClientEvent {
	if x != nil {
		return x.Events
	}
	return nil
}

func (x *JoinResponse_Timeline) GetLimited() bool {
	if x != nil {
		return x.Limited
	}
	return false
}

func (x *JoinResponse_Timeline) GetPrevBatch() string {
	if x != nil {
		return x.PrevBatch
	}
	return ""
}

type JoinResponse_Ephemeral struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Events []*ClientEvent `protobuf:"bytes,1,rep,name=events,proto3" json:"events,omitempty"`
}

func (x *JoinResponse_Ephemeral) Reset() {
	*x = JoinResponse_Ephemeral{}
	if protoimpl.UnsafeEnabled {
		mi := &file_sync_proto_msgTypes[11]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *JoinResponse_Ephemeral) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*JoinResponse_Ephemeral) ProtoMessage() {}

func (x *JoinResponse_Ephemeral) ProtoReflect() protoreflect.Message {
	mi := &file_sync_proto_msgTypes[11]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use JoinResponse_Ephemeral.ProtoReflect.Descriptor instead.
func (*JoinResponse_Ephemeral) Descriptor() ([]byte, []int) {
	return file_sync_proto_rawDescGZIP(), []int{1, 2}
}

func (x *JoinResponse_Ephemeral) GetEvents() []*ClientEvent {
	if x != nil {
		return x.Events
	}
	return nil
}

type JoinResponse_AccountData struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Events []*ClientEvent `protobuf:"bytes,1,rep,name=events,proto3" json:"events,omitempty"`
}

func (x *JoinResponse_AccountData) Reset() {
	*x = JoinResponse_AccountData{}
	if protoimpl.UnsafeEnabled {
		mi := &file_sync_proto_msgTypes[12]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *JoinResponse_AccountData) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*JoinResponse_AccountData) ProtoMessage() {}

func (x *JoinResponse_AccountData) ProtoReflect() protoreflect.Message {
	mi := &file_sync_proto_msgTypes[12]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use JoinResponse_AccountData.ProtoReflect.Descriptor instead.
func (*JoinResponse_AccountData) Descriptor() ([]byte, []int) {
	return file_sync_proto_rawDescGZIP(), []int{1, 3}
}

func (x *JoinResponse_AccountData) GetEvents() []*ClientEvent {
	if x != nil {
		return x.Events
	}
	return nil
}

type InviteResponse_InviteState struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Events []*ClientEvent `protobuf:"bytes,1,rep,name=events,proto3" json:"events,omitempty"`
}

func (x *InviteResponse_InviteState) Reset() {
	*x = InviteResponse_InviteState{}
	if protoimpl.UnsafeEnabled {
		mi := &file_sync_proto_msgTypes[13]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *InviteResponse_InviteState) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*InviteResponse_InviteState) ProtoMessage() {}

func (x *InviteResponse_InviteState) ProtoReflect() protoreflect.Message {
	mi := &file_sync_proto_msgTypes[13]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use InviteResponse_InviteState.ProtoReflect.Descriptor instead.
func (*InviteResponse_InviteState) Descriptor() ([]byte, []int) {
	return file_sync_proto_rawDescGZIP(), []int{2, 0}
}

func (x *InviteResponse_InviteState) GetEvents() []*ClientEvent {
	if x != nil {
		return x.Events
	}
	return nil
}

type LeaveResponse_State struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Events []*ClientEvent `protobuf:"bytes,1,rep,name=events,proto3" json:"events,omitempty"`
}

func (x *LeaveResponse_State) Reset() {
	*x = LeaveResponse_State{}
	if protoimpl.UnsafeEnabled {
		mi := &file_sync_proto_msgTypes[14]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *LeaveResponse_State) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*LeaveResponse_State) ProtoMessage() {}

func (x *LeaveResponse_State) ProtoReflect() protoreflect.Message {
	mi := &file_sync_proto_msgTypes[14]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use LeaveResponse_State.ProtoReflect.Descriptor instead.
func (*LeaveResponse_State) Descriptor() ([]byte, []int) {
	return file_sync_proto_rawDescGZIP(), []int{3, 0}
}

func (x *LeaveResponse_State) GetEvents() []*ClientEvent {
	if x != nil {
		return x.Events
	}
	return nil
}

type LeaveResponse_Timeline struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Events    []*ClientEvent `protobuf:"bytes,1,rep,name=events,proto3" json:"events,omitempty"`
	Limited   bool           `protobuf:"varint,2,opt,name=limited,proto3" json:"limited,omitempty"`
	PrevBatch string         `protobuf:"bytes,3,opt,name=prevBatch,proto3" json:"prevBatch,omitempty"`
}

func (x *LeaveResponse_Timeline) Reset() {
	*x = LeaveResponse_Timeline{}
	if protoimpl.UnsafeEnabled {
		mi := &file_sync_proto_msgTypes[15]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *LeaveResponse_Timeline) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*LeaveResponse_Timeline) ProtoMessage() {}

func (x *LeaveResponse_Timeline) ProtoReflect() protoreflect.Message {
	mi := &file_sync_proto_msgTypes[15]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use LeaveResponse_Timeline.ProtoReflect.Descriptor instead.
func (*LeaveResponse_Timeline) Descriptor() ([]byte, []int) {
	return file_sync_proto_rawDescGZIP(), []int{3, 1}
}

func (x *LeaveResponse_Timeline) GetEvents() []*ClientEvent {
	if x != nil {
		return x.Events
	}
	return nil
}

func (x *LeaveResponse_Timeline) GetLimited() bool {
	if x != nil {
		return x.Limited
	}
	return false
}

func (x *LeaveResponse_Timeline) GetPrevBatch() string {
	if x != nil {
		return x.PrevBatch
	}
	return ""
}

var File_sync_proto protoreflect.FileDescriptor

var file_sync_proto_rawDesc = []byte{
	0x0a, 0x0a, 0x73, 0x79, 0x6e, 0x63, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12, 0x02, 0x70, 0x62,
	0x1a, 0x0c, 0x63, 0x6f, 0x6d, 0x6d, 0x6f, 0x6e, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x22, 0x6b,
	0x0a, 0x13, 0x55, 0x6e, 0x72, 0x65, 0x61, 0x64, 0x4e, 0x6f, 0x74, 0x69, 0x66, 0x69, 0x63, 0x61,
	0x74, 0x69, 0x6f, 0x6e, 0x73, 0x12, 0x26, 0x0a, 0x0e, 0x68, 0x69, 0x67, 0x68, 0x4c, 0x69, 0x67,
	0x68, 0x74, 0x43, 0x6f, 0x75, 0x6e, 0x74, 0x18, 0x01, 0x20, 0x01, 0x28, 0x03, 0x52, 0x0e, 0x68,
	0x69, 0x67, 0x68, 0x4c, 0x69, 0x67, 0x68, 0x74, 0x43, 0x6f, 0x75, 0x6e, 0x74, 0x12, 0x2c, 0x0a,
	0x11, 0x6e, 0x6f, 0x74, 0x69, 0x66, 0x69, 0x63, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x43, 0x6f, 0x75,
	0x6e, 0x74, 0x18, 0x02, 0x20, 0x01, 0x28, 0x03, 0x52, 0x11, 0x6e, 0x6f, 0x74, 0x69, 0x66, 0x69,
	0x63, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x43, 0x6f, 0x75, 0x6e, 0x74, 0x22, 0xab, 0x04, 0x0a, 0x0c,
	0x4a, 0x6f, 0x69, 0x6e, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x2c, 0x0a, 0x05,
	0x73, 0x74, 0x61, 0x74, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x16, 0x2e, 0x70, 0x62,
	0x2e, 0x4a, 0x6f, 0x69, 0x6e, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x2e, 0x53, 0x74,
	0x61, 0x74, 0x65, 0x52, 0x05, 0x73, 0x74, 0x61, 0x74, 0x65, 0x12, 0x35, 0x0a, 0x08, 0x74, 0x69,
	0x6d, 0x65, 0x6c, 0x69, 0x6e, 0x65, 0x18, 0x02, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x19, 0x2e, 0x70,
	0x62, 0x2e, 0x4a, 0x6f, 0x69, 0x6e, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x2e, 0x54,
	0x69, 0x6d, 0x65, 0x6c, 0x69, 0x6e, 0x65, 0x52, 0x08, 0x74, 0x69, 0x6d, 0x65, 0x6c, 0x69, 0x6e,
	0x65, 0x12, 0x38, 0x0a, 0x09, 0x65, 0x70, 0x68, 0x65, 0x6d, 0x65, 0x72, 0x61, 0x6c, 0x18, 0x03,
	0x20, 0x01, 0x28, 0x0b, 0x32, 0x1a, 0x2e, 0x70, 0x62, 0x2e, 0x4a, 0x6f, 0x69, 0x6e, 0x52, 0x65,
	0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x2e, 0x45, 0x70, 0x68, 0x65, 0x6d, 0x65, 0x72, 0x61, 0x6c,
	0x52, 0x09, 0x65, 0x70, 0x68, 0x65, 0x6d, 0x65, 0x72, 0x61, 0x6c, 0x12, 0x3e, 0x0a, 0x0b, 0x61,
	0x63, 0x63, 0x6f, 0x75, 0x6e, 0x74, 0x44, 0x61, 0x74, 0x61, 0x18, 0x04, 0x20, 0x01, 0x28, 0x0b,
	0x32, 0x1c, 0x2e, 0x70, 0x62, 0x2e, 0x4a, 0x6f, 0x69, 0x6e, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e,
	0x73, 0x65, 0x2e, 0x41, 0x63, 0x63, 0x6f, 0x75, 0x6e, 0x74, 0x44, 0x61, 0x74, 0x61, 0x52, 0x0b,
	0x61, 0x63, 0x63, 0x6f, 0x75, 0x6e, 0x74, 0x44, 0x61, 0x74, 0x61, 0x12, 0x2f, 0x0a, 0x06, 0x75,
	0x6e, 0x72, 0x65, 0x61, 0x64, 0x18, 0x05, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x17, 0x2e, 0x70, 0x62,
	0x2e, 0x55, 0x6e, 0x72, 0x65, 0x61, 0x64, 0x4e, 0x6f, 0x74, 0x69, 0x66, 0x69, 0x63, 0x61, 0x74,
	0x69, 0x6f, 0x6e, 0x73, 0x52, 0x06, 0x75, 0x6e, 0x72, 0x65, 0x61, 0x64, 0x1a, 0x30, 0x0a, 0x05,
	0x53, 0x74, 0x61, 0x74, 0x65, 0x12, 0x27, 0x0a, 0x06, 0x65, 0x76, 0x65, 0x6e, 0x74, 0x73, 0x18,
	0x01, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x0f, 0x2e, 0x70, 0x62, 0x2e, 0x43, 0x6c, 0x69, 0x65, 0x6e,
	0x74, 0x45, 0x76, 0x65, 0x6e, 0x74, 0x52, 0x06, 0x65, 0x76, 0x65, 0x6e, 0x74, 0x73, 0x1a, 0x6b,
	0x0a, 0x08, 0x54, 0x69, 0x6d, 0x65, 0x6c, 0x69, 0x6e, 0x65, 0x12, 0x27, 0x0a, 0x06, 0x65, 0x76,
	0x65, 0x6e, 0x74, 0x73, 0x18, 0x01, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x0f, 0x2e, 0x70, 0x62, 0x2e,
	0x43, 0x6c, 0x69, 0x65, 0x6e, 0x74, 0x45, 0x76, 0x65, 0x6e, 0x74, 0x52, 0x06, 0x65, 0x76, 0x65,
	0x6e, 0x74, 0x73, 0x12, 0x18, 0x0a, 0x07, 0x6c, 0x69, 0x6d, 0x69, 0x74, 0x65, 0x64, 0x18, 0x02,
	0x20, 0x01, 0x28, 0x08, 0x52, 0x07, 0x6c, 0x69, 0x6d, 0x69, 0x74, 0x65, 0x64, 0x12, 0x1c, 0x0a,
	0x09, 0x70, 0x72, 0x65, 0x76, 0x42, 0x61, 0x74, 0x63, 0x68, 0x18, 0x03, 0x20, 0x01, 0x28, 0x09,
	0x52, 0x09, 0x70, 0x72, 0x65, 0x76, 0x42, 0x61, 0x74, 0x63, 0x68, 0x1a, 0x34, 0x0a, 0x09, 0x45,
	0x70, 0x68, 0x65, 0x6d, 0x65, 0x72, 0x61, 0x6c, 0x12, 0x27, 0x0a, 0x06, 0x65, 0x76, 0x65, 0x6e,
	0x74, 0x73, 0x18, 0x01, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x0f, 0x2e, 0x70, 0x62, 0x2e, 0x43, 0x6c,
	0x69, 0x65, 0x6e, 0x74, 0x45, 0x76, 0x65, 0x6e, 0x74, 0x52, 0x06, 0x65, 0x76, 0x65, 0x6e, 0x74,
	0x73, 0x1a, 0x36, 0x0a, 0x0b, 0x41, 0x63, 0x63, 0x6f, 0x75, 0x6e, 0x74, 0x44, 0x61, 0x74, 0x61,
	0x12, 0x27, 0x0a, 0x06, 0x65, 0x76, 0x65, 0x6e, 0x74, 0x73, 0x18, 0x01, 0x20, 0x03, 0x28, 0x0b,
	0x32, 0x0f, 0x2e, 0x70, 0x62, 0x2e, 0x43, 0x6c, 0x69, 0x65, 0x6e, 0x74, 0x45, 0x76, 0x65, 0x6e,
	0x74, 0x52, 0x06, 0x65, 0x76, 0x65, 0x6e, 0x74, 0x73, 0x22, 0x8a, 0x01, 0x0a, 0x0e, 0x49, 0x6e,
	0x76, 0x69, 0x74, 0x65, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x40, 0x0a, 0x0b,
	0x69, 0x6e, 0x76, 0x69, 0x74, 0x65, 0x53, 0x74, 0x61, 0x74, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28,
	0x0b, 0x32, 0x1e, 0x2e, 0x70, 0x62, 0x2e, 0x49, 0x6e, 0x76, 0x69, 0x74, 0x65, 0x52, 0x65, 0x73,
	0x70, 0x6f, 0x6e, 0x73, 0x65, 0x2e, 0x49, 0x6e, 0x76, 0x69, 0x74, 0x65, 0x53, 0x74, 0x61, 0x74,
	0x65, 0x52, 0x0b, 0x69, 0x6e, 0x76, 0x69, 0x74, 0x65, 0x53, 0x74, 0x61, 0x74, 0x65, 0x1a, 0x36,
	0x0a, 0x0b, 0x49, 0x6e, 0x76, 0x69, 0x74, 0x65, 0x53, 0x74, 0x61, 0x74, 0x65, 0x12, 0x27, 0x0a,
	0x06, 0x65, 0x76, 0x65, 0x6e, 0x74, 0x73, 0x18, 0x01, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x0f, 0x2e,
	0x70, 0x62, 0x2e, 0x43, 0x6c, 0x69, 0x65, 0x6e, 0x74, 0x45, 0x76, 0x65, 0x6e, 0x74, 0x52, 0x06,
	0x65, 0x76, 0x65, 0x6e, 0x74, 0x73, 0x22, 0x95, 0x02, 0x0a, 0x0d, 0x4c, 0x65, 0x61, 0x76, 0x65,
	0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x2d, 0x0a, 0x05, 0x73, 0x74, 0x61, 0x74,
	0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x17, 0x2e, 0x70, 0x62, 0x2e, 0x4c, 0x65, 0x61,
	0x76, 0x65, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x2e, 0x53, 0x74, 0x61, 0x74, 0x65,
	0x52, 0x05, 0x73, 0x74, 0x61, 0x74, 0x65, 0x12, 0x36, 0x0a, 0x08, 0x74, 0x69, 0x6d, 0x65, 0x6c,
	0x69, 0x6e, 0x65, 0x18, 0x02, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x1a, 0x2e, 0x70, 0x62, 0x2e, 0x4c,
	0x65, 0x61, 0x76, 0x65, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x2e, 0x54, 0x69, 0x6d,
	0x65, 0x6c, 0x69, 0x6e, 0x65, 0x52, 0x08, 0x74, 0x69, 0x6d, 0x65, 0x6c, 0x69, 0x6e, 0x65, 0x1a,
	0x30, 0x0a, 0x05, 0x53, 0x74, 0x61, 0x74, 0x65, 0x12, 0x27, 0x0a, 0x06, 0x65, 0x76, 0x65, 0x6e,
	0x74, 0x73, 0x18, 0x01, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x0f, 0x2e, 0x70, 0x62, 0x2e, 0x43, 0x6c,
	0x69, 0x65, 0x6e, 0x74, 0x45, 0x76, 0x65, 0x6e, 0x74, 0x52, 0x06, 0x65, 0x76, 0x65, 0x6e, 0x74,
	0x73, 0x1a, 0x6b, 0x0a, 0x08, 0x54, 0x69, 0x6d, 0x65, 0x6c, 0x69, 0x6e, 0x65, 0x12, 0x27, 0x0a,
	0x06, 0x65, 0x76, 0x65, 0x6e, 0x74, 0x73, 0x18, 0x01, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x0f, 0x2e,
	0x70, 0x62, 0x2e, 0x43, 0x6c, 0x69, 0x65, 0x6e, 0x74, 0x45, 0x76, 0x65, 0x6e, 0x74, 0x52, 0x06,
	0x65, 0x76, 0x65, 0x6e, 0x74, 0x73, 0x12, 0x18, 0x0a, 0x07, 0x6c, 0x69, 0x6d, 0x69, 0x74, 0x65,
	0x64, 0x18, 0x02, 0x20, 0x01, 0x28, 0x08, 0x52, 0x07, 0x6c, 0x69, 0x6d, 0x69, 0x74, 0x65, 0x64,
	0x12, 0x1c, 0x0a, 0x09, 0x70, 0x72, 0x65, 0x76, 0x42, 0x61, 0x74, 0x63, 0x68, 0x18, 0x03, 0x20,
	0x01, 0x28, 0x09, 0x52, 0x09, 0x70, 0x72, 0x65, 0x76, 0x42, 0x61, 0x74, 0x63, 0x68, 0x22, 0xd8,
	0x02, 0x0a, 0x06, 0x50, 0x75, 0x73, 0x68, 0x65, 0x72, 0x12, 0x1a, 0x0a, 0x08, 0x75, 0x73, 0x65,
	0x72, 0x4e, 0x61, 0x6d, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x08, 0x75, 0x73, 0x65,
	0x72, 0x4e, 0x61, 0x6d, 0x65, 0x12, 0x1a, 0x0a, 0x08, 0x64, 0x65, 0x76, 0x69, 0x63, 0x65, 0x49,
	0x44, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x08, 0x64, 0x65, 0x76, 0x69, 0x63, 0x65, 0x49,
	0x44, 0x12, 0x18, 0x0a, 0x07, 0x70, 0x75, 0x73, 0x68, 0x4b, 0x65, 0x79, 0x18, 0x03, 0x20, 0x01,
	0x28, 0x09, 0x52, 0x07, 0x70, 0x75, 0x73, 0x68, 0x4b, 0x65, 0x79, 0x12, 0x1c, 0x0a, 0x09, 0x70,
	0x75, 0x73, 0x68, 0x4b, 0x65, 0x79, 0x54, 0x73, 0x18, 0x04, 0x20, 0x01, 0x28, 0x03, 0x52, 0x09,
	0x70, 0x75, 0x73, 0x68, 0x4b, 0x65, 0x79, 0x54, 0x73, 0x12, 0x12, 0x0a, 0x04, 0x6b, 0x69, 0x6e,
	0x64, 0x18, 0x05, 0x20, 0x01, 0x28, 0x09, 0x52, 0x04, 0x6b, 0x69, 0x6e, 0x64, 0x12, 0x14, 0x0a,
	0x05, 0x61, 0x70, 0x70, 0x49, 0x64, 0x18, 0x06, 0x20, 0x01, 0x28, 0x09, 0x52, 0x05, 0x61, 0x70,
	0x70, 0x49, 0x64, 0x12, 0x26, 0x0a, 0x0e, 0x61, 0x70, 0x70, 0x44, 0x69, 0x73, 0x70, 0x6c, 0x61,
	0x79, 0x4e, 0x61, 0x6d, 0x65, 0x18, 0x07, 0x20, 0x01, 0x28, 0x09, 0x52, 0x0e, 0x61, 0x70, 0x70,
	0x44, 0x69, 0x73, 0x70, 0x6c, 0x61, 0x79, 0x4e, 0x61, 0x6d, 0x65, 0x12, 0x2c, 0x0a, 0x11, 0x64,
	0x65, 0x76, 0x69, 0x63, 0x65, 0x44, 0x69, 0x73, 0x70, 0x6c, 0x61, 0x79, 0x4e, 0x61, 0x6d, 0x65,
	0x18, 0x08, 0x20, 0x01, 0x28, 0x09, 0x52, 0x11, 0x64, 0x65, 0x76, 0x69, 0x63, 0x65, 0x44, 0x69,
	0x73, 0x70, 0x6c, 0x61, 0x79, 0x4e, 0x61, 0x6d, 0x65, 0x12, 0x1e, 0x0a, 0x0a, 0x70, 0x72, 0x6f,
	0x66, 0x69, 0x6c, 0x65, 0x54, 0x61, 0x67, 0x18, 0x09, 0x20, 0x01, 0x28, 0x09, 0x52, 0x0a, 0x70,
	0x72, 0x6f, 0x66, 0x69, 0x6c, 0x65, 0x54, 0x61, 0x67, 0x12, 0x12, 0x0a, 0x04, 0x6c, 0x61, 0x6e,
	0x67, 0x18, 0x0a, 0x20, 0x01, 0x28, 0x09, 0x52, 0x04, 0x6c, 0x61, 0x6e, 0x67, 0x12, 0x16, 0x0a,
	0x06, 0x61, 0x70, 0x70, 0x65, 0x6e, 0x64, 0x18, 0x0b, 0x20, 0x01, 0x28, 0x08, 0x52, 0x06, 0x61,
	0x70, 0x70, 0x65, 0x6e, 0x64, 0x12, 0x12, 0x0a, 0x04, 0x64, 0x61, 0x74, 0x61, 0x18, 0x0c, 0x20,
	0x01, 0x28, 0x0c, 0x52, 0x04, 0x64, 0x61, 0x74, 0x61, 0x22, 0x2f, 0x0a, 0x07, 0x50, 0x75, 0x73,
	0x68, 0x65, 0x72, 0x73, 0x12, 0x24, 0x0a, 0x07, 0x70, 0x75, 0x73, 0x68, 0x65, 0x72, 0x73, 0x18,
	0x01, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x0a, 0x2e, 0x70, 0x62, 0x2e, 0x50, 0x75, 0x73, 0x68, 0x65,
	0x72, 0x52, 0x07, 0x70, 0x75, 0x73, 0x68, 0x65, 0x72, 0x73, 0x22, 0x5f, 0x0a, 0x0d, 0x50, 0x75,
	0x73, 0x68, 0x43, 0x6f, 0x6e, 0x64, 0x69, 0x74, 0x69, 0x6f, 0x6e, 0x12, 0x12, 0x0a, 0x04, 0x6b,
	0x69, 0x6e, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x04, 0x6b, 0x69, 0x6e, 0x64, 0x12,
	0x10, 0x0a, 0x03, 0x6b, 0x65, 0x79, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x03, 0x6b, 0x65,
	0x79, 0x12, 0x18, 0x0a, 0x07, 0x70, 0x61, 0x74, 0x74, 0x65, 0x72, 0x6e, 0x18, 0x03, 0x20, 0x01,
	0x28, 0x09, 0x52, 0x07, 0x70, 0x61, 0x74, 0x74, 0x65, 0x72, 0x6e, 0x12, 0x0e, 0x0a, 0x02, 0x69,
	0x73, 0x18, 0x04, 0x20, 0x01, 0x28, 0x09, 0x52, 0x02, 0x69, 0x73, 0x22, 0xbd, 0x01, 0x0a, 0x08,
	0x50, 0x75, 0x73, 0x68, 0x52, 0x75, 0x6c, 0x65, 0x12, 0x18, 0x0a, 0x07, 0x41, 0x63, 0x74, 0x69,
	0x6f, 0x6e, 0x73, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0c, 0x52, 0x07, 0x41, 0x63, 0x74, 0x69, 0x6f,
	0x6e, 0x73, 0x12, 0x18, 0x0a, 0x07, 0x64, 0x65, 0x66, 0x61, 0x75, 0x6c, 0x74, 0x18, 0x02, 0x20,
	0x01, 0x28, 0x08, 0x52, 0x07, 0x64, 0x65, 0x66, 0x61, 0x75, 0x6c, 0x74, 0x12, 0x18, 0x0a, 0x07,
	0x65, 0x6e, 0x61, 0x62, 0x6c, 0x65, 0x64, 0x18, 0x03, 0x20, 0x01, 0x28, 0x08, 0x52, 0x07, 0x65,
	0x6e, 0x61, 0x62, 0x6c, 0x65, 0x64, 0x12, 0x16, 0x0a, 0x06, 0x72, 0x75, 0x6c, 0x65, 0x49, 0x64,
	0x18, 0x04, 0x20, 0x01, 0x28, 0x09, 0x52, 0x06, 0x72, 0x75, 0x6c, 0x65, 0x49, 0x64, 0x12, 0x31,
	0x0a, 0x0a, 0x63, 0x6f, 0x6e, 0x64, 0x69, 0x74, 0x69, 0x6f, 0x6e, 0x73, 0x18, 0x05, 0x20, 0x03,
	0x28, 0x0b, 0x32, 0x11, 0x2e, 0x70, 0x62, 0x2e, 0x50, 0x75, 0x73, 0x68, 0x43, 0x6f, 0x6e, 0x64,
	0x69, 0x74, 0x69, 0x6f, 0x6e, 0x52, 0x0a, 0x63, 0x6f, 0x6e, 0x64, 0x69, 0x74, 0x69, 0x6f, 0x6e,
	0x73, 0x12, 0x18, 0x0a, 0x07, 0x70, 0x61, 0x74, 0x74, 0x65, 0x72, 0x6e, 0x18, 0x06, 0x20, 0x01,
	0x28, 0x09, 0x52, 0x07, 0x70, 0x61, 0x74, 0x74, 0x65, 0x72, 0x6e, 0x22, 0xcd, 0x01, 0x0a, 0x05,
	0x52, 0x75, 0x6c, 0x65, 0x73, 0x12, 0x26, 0x0a, 0x07, 0x63, 0x6f, 0x6e, 0x74, 0x65, 0x6e, 0x74,
	0x18, 0x01, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x0c, 0x2e, 0x70, 0x62, 0x2e, 0x50, 0x75, 0x73, 0x68,
	0x52, 0x75, 0x6c, 0x65, 0x52, 0x07, 0x63, 0x6f, 0x6e, 0x74, 0x65, 0x6e, 0x74, 0x12, 0x28, 0x0a,
	0x08, 0x6f, 0x76, 0x65, 0x72, 0x72, 0x69, 0x64, 0x65, 0x18, 0x02, 0x20, 0x03, 0x28, 0x0b, 0x32,
	0x0c, 0x2e, 0x70, 0x62, 0x2e, 0x50, 0x75, 0x73, 0x68, 0x52, 0x75, 0x6c, 0x65, 0x52, 0x08, 0x6f,
	0x76, 0x65, 0x72, 0x72, 0x69, 0x64, 0x65, 0x12, 0x20, 0x0a, 0x04, 0x72, 0x6f, 0x6f, 0x6d, 0x18,
	0x03, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x0c, 0x2e, 0x70, 0x62, 0x2e, 0x50, 0x75, 0x73, 0x68, 0x52,
	0x75, 0x6c, 0x65, 0x52, 0x04, 0x72, 0x6f, 0x6f, 0x6d, 0x12, 0x24, 0x0a, 0x06, 0x73, 0x65, 0x6e,
	0x64, 0x65, 0x72, 0x18, 0x04, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x0c, 0x2e, 0x70, 0x62, 0x2e, 0x50,
	0x75, 0x73, 0x68, 0x52, 0x75, 0x6c, 0x65, 0x52, 0x06, 0x73, 0x65, 0x6e, 0x64, 0x65, 0x72, 0x12,
	0x2a, 0x0a, 0x09, 0x75, 0x6e, 0x64, 0x65, 0x72, 0x52, 0x69, 0x64, 0x65, 0x18, 0x05, 0x20, 0x03,
	0x28, 0x0b, 0x32, 0x0c, 0x2e, 0x70, 0x62, 0x2e, 0x50, 0x75, 0x73, 0x68, 0x52, 0x75, 0x6c, 0x65,
	0x52, 0x09, 0x75, 0x6e, 0x64, 0x65, 0x72, 0x52, 0x69, 0x64, 0x65, 0x42, 0x07, 0x5a, 0x05, 0x2e,
	0x2f, 0x3b, 0x70, 0x62, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_sync_proto_rawDescOnce sync.Once
	file_sync_proto_rawDescData = file_sync_proto_rawDesc
)

func file_sync_proto_rawDescGZIP() []byte {
	file_sync_proto_rawDescOnce.Do(func() {
		file_sync_proto_rawDescData = protoimpl.X.CompressGZIP(file_sync_proto_rawDescData)
	})
	return file_sync_proto_rawDescData
}

var file_sync_proto_msgTypes = make([]protoimpl.MessageInfo, 16)
var file_sync_proto_goTypes = []interface{}{
	(*UnreadNotifications)(nil),        // 0: pb.UnreadNotifications
	(*JoinResponse)(nil),               // 1: pb.JoinResponse
	(*InviteResponse)(nil),             // 2: pb.InviteResponse
	(*LeaveResponse)(nil),              // 3: pb.LeaveResponse
	(*Pusher)(nil),                     // 4: pb.Pusher
	(*Pushers)(nil),                    // 5: pb.Pushers
	(*PushCondition)(nil),              // 6: pb.PushCondition
	(*PushRule)(nil),                   // 7: pb.PushRule
	(*Rules)(nil),                      // 8: pb.Rules
	(*JoinResponse_State)(nil),         // 9: pb.JoinResponse.State
	(*JoinResponse_Timeline)(nil),      // 10: pb.JoinResponse.Timeline
	(*JoinResponse_Ephemeral)(nil),     // 11: pb.JoinResponse.Ephemeral
	(*JoinResponse_AccountData)(nil),   // 12: pb.JoinResponse.AccountData
	(*InviteResponse_InviteState)(nil), // 13: pb.InviteResponse.InviteState
	(*LeaveResponse_State)(nil),        // 14: pb.LeaveResponse.State
	(*LeaveResponse_Timeline)(nil),     // 15: pb.LeaveResponse.Timeline
	(*ClientEvent)(nil),                // 16: pb.ClientEvent
}
var file_sync_proto_depIdxs = []int32{
	9,  // 0: pb.JoinResponse.state:type_name -> pb.JoinResponse.State
	10, // 1: pb.JoinResponse.timeline:type_name -> pb.JoinResponse.Timeline
	11, // 2: pb.JoinResponse.ephemeral:type_name -> pb.JoinResponse.Ephemeral
	12, // 3: pb.JoinResponse.accountData:type_name -> pb.JoinResponse.AccountData
	0,  // 4: pb.JoinResponse.unread:type_name -> pb.UnreadNotifications
	13, // 5: pb.InviteResponse.inviteState:type_name -> pb.InviteResponse.InviteState
	14, // 6: pb.LeaveResponse.state:type_name -> pb.LeaveResponse.State
	15, // 7: pb.LeaveResponse.timeline:type_name -> pb.LeaveResponse.Timeline
	4,  // 8: pb.Pushers.pushers:type_name -> pb.Pusher
	6,  // 9: pb.PushRule.conditions:type_name -> pb.PushCondition
	7,  // 10: pb.Rules.content:type_name -> pb.PushRule
	7,  // 11: pb.Rules.override:type_name -> pb.PushRule
	7,  // 12: pb.Rules.room:type_name -> pb.PushRule
	7,  // 13: pb.Rules.sender:type_name -> pb.PushRule
	7,  // 14: pb.Rules.underRide:type_name -> pb.PushRule
	16, // 15: pb.JoinResponse.State.events:type_name -> pb.ClientEvent
	16, // 16: pb.JoinResponse.Timeline.events:type_name -> pb.ClientEvent
	16, // 17: pb.JoinResponse.Ephemeral.events:type_name -> pb.ClientEvent
	16, // 18: pb.JoinResponse.AccountData.events:type_name -> pb.ClientEvent
	16, // 19: pb.InviteResponse.InviteState.events:type_name -> pb.ClientEvent
	16, // 20: pb.LeaveResponse.State.events:type_name -> pb.ClientEvent
	16, // 21: pb.LeaveResponse.Timeline.events:type_name -> pb.ClientEvent
	22, // [22:22] is the sub-list for method output_type
	22, // [22:22] is the sub-list for method input_type
	22, // [22:22] is the sub-list for extension type_name
	22, // [22:22] is the sub-list for extension extendee
	0,  // [0:22] is the sub-list for field type_name
}

func init() { file_sync_proto_init() }
func file_sync_proto_init() {
	if File_sync_proto != nil {
		return
	}
	file_common_proto_init()
	if !protoimpl.UnsafeEnabled {
		file_sync_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*UnreadNotifications); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_sync_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*JoinResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_sync_proto_msgTypes[2].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*InviteResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_sync_proto_msgTypes[3].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*LeaveResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_sync_proto_msgTypes[4].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Pusher); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_sync_proto_msgTypes[5].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Pushers); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_sync_proto_msgTypes[6].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*PushCondition); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_sync_proto_msgTypes[7].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*PushRule); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_sync_proto_msgTypes[8].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Rules); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_sync_proto_msgTypes[9].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*JoinResponse_State); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_sync_proto_msgTypes[10].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*JoinResponse_Timeline); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_sync_proto_msgTypes[11].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*JoinResponse_Ephemeral); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_sync_proto_msgTypes[12].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*JoinResponse_AccountData); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_sync_proto_msgTypes[13].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*InviteResponse_InviteState); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_sync_proto_msgTypes[14].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*LeaveResponse_State); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_sync_proto_msgTypes[15].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*LeaveResponse_Timeline); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_sync_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   16,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_sync_proto_goTypes,
		DependencyIndexes: file_sync_proto_depIdxs,
		MessageInfos:      file_sync_proto_msgTypes,
	}.Build()
	File_sync_proto = out.File
	file_sync_proto_rawDesc = nil
	file_sync_proto_goTypes = nil
	file_sync_proto_depIdxs = nil
}
